# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d58e495d0d84cdf65c33c945bf22de88464b189128321b6d7d2cb52e3a09192f02dc43b817a759822c9a4ad083d7c2268f29066d2fa68c31cb247167552d9df2

test:
  secret_key_base: 7e0de3397420a673c665a0921fa1c7b0f55b810ba265a01717df9089484ce2b0f96c23a3c02ceafa787a7aabc898f0e7a0294ce49e951c854d1dd56d9b4374d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
